# Generated by Django 4.2.16 on 2024-12-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='therapist',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
    ]
