# Generated by Django 4.2.16 on 2024-12-02 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_category_alter_service_options_alter_service_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.category', verbose_name='دسته بندی'),
        ),
    ]
