# Generated by Django 4.2.16 on 2024-12-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_category_alter_service_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
    ]
