# Generated by Django 4.2.17 on 2024-12-13 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0009_alter_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_time', models.TimeField(verbose_name='زمان ترجیحی')),
                ('special_condition', models.TextField(verbose_name='شرایط خاص')),
                ('same_gender', models.BooleanField(default=True, verbose_name='درمانگر همجنس')),
                ('created_Time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت سفارش')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.category', verbose_name='دسته بندی')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service', verbose_name='خدمت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
