# Generated by Django 4.2.17 on 2024-12-14 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_disease_user_gender_user_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0010_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_time', models.TimeField(verbose_name='زمان ترجیحی')),
                ('special_condition', models.TextField(blank=True, null=True, verbose_name='شرایط خاص')),
                ('same_gender', models.BooleanField(default=True, verbose_name='درمانگر همجنس')),
                ('created_Time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت سفارش')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.address')),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service', verbose_name='خدمت'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
