# Generated by Django 4.2.17 on 2024-12-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_notification'),
        ('services', '0011_order_alter_service_options_delete_servicerequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.address', verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان ترجیحی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_condition',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='شرایط خاص'),
        ),
    ]
