# Generated by Django 4.2.17 on 2024-12-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_order_address_alter_order_preferred_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_Time',
            new_name='created_time',
        ),
    ]
