# Generated by Django 4.2.17 on 2024-12-23 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_rename_is_taken_reminder_is_read'),
        ('services', '0013_rename_created_time_order_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.familymember', verbose_name='برای خودتان یا :'),
        ),
    ]
