# Generated by Django 4.2.17 on 2024-12-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.FloatField(verbose_name='قیمت'),
        ),
    ]
