# Generated by Django 4.2.17 on 2024-12-25 04:03

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_service_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='انتخاب تاریخ'),
        ),
    ]
