# Generated by Django 4.2.17 on 2024-12-12 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_email_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='عضویت'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('detail', models.TextField(verbose_name='جزئیات')),
                ('location_link', models.URLField(verbose_name='لینک گوگل مپ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='مالک آدرس')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس  ها',
            },
        ),
    ]
