# Generated by Django 4.2.17 on 2024-12-12 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_address_location_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='مالک آدرس'),
        ),
    ]
