# Generated by Django 4.2.17 on 2024-12-13 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_address_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='روز تولد'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthmonth',
            field=models.CharField(blank=True, choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], max_length=15, null=True, verbose_name='ماه تولد'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthyear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1450)], verbose_name='سال تولد'),
        ),
    ]
