# Generated by Django 4.2.17 on 2024-12-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_birthday_user_birthmonth_user_birthyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disease',
            field=models.CharField(blank=True, choices=[('دیابت', 'دیابت'), ('سرطان', 'سرطان'), ('بیماری قلبی', 'بیماری قلبی'), ('فشار خون', 'فشار خون'), ('بیماری های ریوی', 'بیماری های ریوی'), ('نارسایی کلیه', 'نارسایی کلیه'), ('کم خونی', 'کم خونی'), ('بیماری های مادرزادی', 'بیماری های مادرزادی'), ('مشکلات کبدی و گوارشی', 'مشکلات کبدی و گوارشی'), ('سایر', 'سایر')], max_length=100, null=True, verbose_name='بیماری های زمینه ای'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('زن', 'زن'), ('مرد', 'مرد')], max_length=3, null=True, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthmonth',
            field=models.CharField(blank=True, choices=[('فروردین', 'فروردین'), ('اردیبهشت', 'اردیبهشت'), ('خرداد', 'خرداد'), ('تیر', 'تیر'), ('مرداد', 'مرداد'), ('شهریور', 'شهریور'), ('مهر', 'مهر'), ('آبان', 'آبان'), ('آذر', 'آذر'), ('دی', 'دی'), ('بهمن', 'بهمن'), ('اسفند', 'اسفند')], max_length=15, null=True, verbose_name='ماه تولد'),
        ),
    ]
