# Generated by Django 4.2.17 on 2024-12-17 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام دارو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات دارو')),
                ('dose', models.CharField(max_length=50, verbose_name='دوز مصرف')),
                ('useage_way', models.CharField(choices=[('موضعی', 'موضعی'), ('خوراکی', 'خوراکی'), ('تزریقی', 'تزریقی'), ('مقعدی', 'مقعدی'), ('سایر', 'سایر')], max_length=50, verbose_name='نحوه مصرف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده دارو')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.DurationField(verbose_name='فاصله زمانی مصرف')),
                ('start_date', models.DateTimeField(verbose_name='زمان شروع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.medicine', verbose_name='دارو')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_by', to=settings.AUTH_USER_MODEL, verbose_name='تجویز کننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='مصرف کننده')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField(verbose_name='زمان یادآوری')),
                ('is_taken', models.BooleanField(default=False, verbose_name='مصرف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='account.prescription', verbose_name='نسخه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مصرف کننده')),
            ],
        ),
    ]
