# Generated by Django 4.2.17 on 2024-12-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_prescription_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=' تعداد مصرف'),
        ),
    ]
