# Generated by Django 4.2.17 on 2024-12-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_prescription_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='start_date',
            field=models.DateTimeField(verbose_name='زمان شروع'),
        ),
    ]
