# Generated by Django 4.2.17 on 2024-12-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_prescription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع'),
        ),
    ]
