# Generated by Django 4.2.17 on 2024-12-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_prescription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
