# Generated by Django 4.2.17 on 2024-12-19 00:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_reminder_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='روز تولد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birthmonth',
            field=models.CharField(choices=[('فروردین', 'فروردین'), ('اردیبهشت', 'اردیبهشت'), ('خرداد', 'خرداد'), ('تیر', 'تیر'), ('مرداد', 'مرداد'), ('شهریور', 'شهریور'), ('مهر', 'مهر'), ('آبان', 'آبان'), ('آذر', 'آذر'), ('دی', 'دی'), ('بهمن', 'بهمن'), ('اسفند', 'اسفند')], default='مهر', max_length=15, verbose_name='ماه تولد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birthyear',
            field=models.IntegerField(default=1360, validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1450)], verbose_name='سال تولد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('زن', 'زن'), ('مرد', 'مرد')], default='مرد', max_length=3, verbose_name='جنسیت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=912, verbose_name='شماره همراه'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پت')),
                ('gender', models.CharField(choices=[('دختر', 'دختر'), ('پسر', 'پسر')], max_length=4, verbose_name='جنسیت')),
                ('birthyear', models.IntegerField(validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1450)], verbose_name='سال تولد')),
                ('birthmonth', models.CharField(choices=[('فروردین', 'فروردین'), ('اردیبهشت', 'اردیبهشت'), ('خرداد', 'خرداد'), ('تیر', 'تیر'), ('مرداد', 'مرداد'), ('شهریور', 'شهریور'), ('مهر', 'مهر'), ('آبان', 'آبان'), ('آذر', 'آذر'), ('دی', 'دی'), ('بهمن', 'بهمن'), ('اسفند', 'اسفند')], max_length=15, verbose_name='ماه تولد')),
                ('birthday', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='روز تولد')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pets', to=settings.AUTH_USER_MODEL, verbose_name='صاحب')),
            ],
        ),
    ]
