# Generated by Django 4.2.17 on 2024-12-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_user_birthday_alter_user_birthmonth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='race',
            field=models.CharField(default='ژرمن', max_length=40, verbose_name='نژاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('سگ', 'سگ'), ('گربه', 'گربه'), ('خزنده', 'خزنده'), ('پرنده', 'پرنده'), ('جونده', 'جونده'), ('آبزی', 'آبزی'), ('سایر', 'سایر')], default='سگ', max_length=20, verbose_name='گونه'),
            preserve_default=False,
        ),
    ]
