# Generated by Django 4.2.17 on 2024-12-20 00:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_pet_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'پت', 'verbose_name_plural': 'پت  ها'},
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('relation', models.CharField(max_length=50, verbose_name='نسبت')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='عضویت')),
                ('birthyear', models.IntegerField(validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1450)], verbose_name='سال تولد')),
                ('birthmonth', models.CharField(choices=[('فروردین', 'فروردین'), ('اردیبهشت', 'اردیبهشت'), ('خرداد', 'خرداد'), ('تیر', 'تیر'), ('مرداد', 'مرداد'), ('شهریور', 'شهریور'), ('مهر', 'مهر'), ('آبان', 'آبان'), ('آذر', 'آذر'), ('دی', 'دی'), ('بهمن', 'بهمن'), ('اسفند', 'اسفند')], max_length=15, verbose_name='ماه تولد')),
                ('birthday', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='روز تولد')),
                ('phone', models.IntegerField(verbose_name='شماره همراه')),
                ('gender', models.CharField(choices=[('زن', 'زن'), ('مرد', 'مرد')], max_length=3, verbose_name='جنسیت')),
                ('disease', models.CharField(blank=True, choices=[('دیابت', 'دیابت'), ('سرطان', 'سرطان'), ('بیماری قلبی', 'بیماری قلبی'), ('فشار خون', 'فشار خون'), ('بیماری های ریوی', 'بیماری های ریوی'), ('نارسایی کلیه', 'نارسایی کلیه'), ('کم خونی', 'کم خونی'), ('بیماری های مادرزادی', 'بیماری های مادرزادی'), ('مشکلات کبدی و گوارشی', 'مشکلات کبدی و گوارشی'), ('سایر', 'سایر')], max_length=100, null=True, verbose_name='بیماری های زمینه ای')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL, verbose_name='والد')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضا',
            },
        ),
    ]
