# Generated by Django 4.2.17 on 2024-12-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_pet_options_familymember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='is_taken',
            new_name='is_read',
        ),
    ]
