# Generated by Django 4.2.17 on 2024-12-29 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_user_subscription_info_webpushsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_info',
        ),
    ]
