# Generated by Django 4.2.17 on 2024-12-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_user_subscription_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
