# Generated by Django 4.2.17 on 2024-12-30 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_user_subscription_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_info',
        ),
    ]
