# Generated by Django 5.1.4 on 2024-12-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_remove_user_subscription_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
