# Generated by Django 5.1.4 on 2024-12-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_user_subscription_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='interval',
            field=models.PositiveIntegerField(verbose_name='فاصله زمانی مصرف'),
        ),
    ]
