# Generated by Django 5.1.4 on 2025-01-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_user_birthday_alter_user_birthmonth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='شماره همراه'),
        ),
    ]
